name = "m3u-proxy"
type = "javascript"

account_id = "Account ID: 1234567890abcdef1234567890abcdef"
workers_dev = true
compatibility_date = "2025-05-17"

[build]
upload.format = "modules"

[dev]
port = 8787
